# Generated by Django 3.1.4 on 2020-12-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
